[package]
name = "leptos-chartistry"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console_error_panic_hook = "0.1"
console_log = "1.0"
leptos = { version = "0.5", features = ["csr"] }
log = "0.4"
web-sys = { version = "0.3", features = ["DomRectReadOnly"] }
