[package]
name = "leptos-chartistry"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
console_error_panic_hook = "0.1"
console_log = "1.0"
leptos = { version = "0.6", features = ["csr"] }
leptos-use = "0.10"
leptos_meta = { version = "0.6", features = ["csr"] }
log = "0.4"
web-sys = { version = "0.3", features = ["DomRectReadOnly"] }
