[package]
name = "leptos-chartistry"
version = "0.1.0"
authors = [ "Joshua McQuistan <joshua.mcquistan@feral.io>" ]
edition = "2021"
description = "Chartistry is a charting library for Leptos"
documentation = "https://docs.rs/leptos-chartistry"
repository = "https://github.com/feral-dot-io/leptos-chartistry"
license = "MPL-2.0"
keywords = [ "leptos", "wasm", "charts" ]
categories = [ "graphics", "gui", "wasm", "web-programming" ]

[dependencies]
chrono = "0.4"
leptos = { version = "0.6", features = ["csr"] }
leptos-use = "0.10"
log = "0.4"
web-sys = { version = "0.3", features = ["DomRectReadOnly"] }

# Demo dependencies
console_error_panic_hook = { version = "0.1", optional = true }
console_log = { version = "1.0", optional = true }
leptos_meta = { version = "0.6", features = ["csr"], optional = true }

[features]
build-demo = [ "console_error_panic_hook", "console_log", "leptos_meta" ]

[[bin]]
name = "demo"
required-features = [ "build-demo" ]
