[package]
name = "my_example_ssr"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
axum = { version = "0.7", optional = true }
console_error_panic_hook = "0.1"
console_log = "1.0"
leptos = { version = "0.6", features = [ "hydrate" ] }
leptos_axum = { version = "0.6", optional = true }
# Use leptos_chartistry.version = "..." instead
leptos-chartistry.path = "../../leptos-chartistry"
leptos_router.version = "0.6"
log = "0.4"
tokio = { version = "1.40", features = [ "full" ], optional = true }
wasm-bindgen = "0.2.93"

[features]
hydrate = ["leptos/hydrate"]
ssr = [
  "dep:axum",
  "leptos/ssr",
  "leptos_router/ssr",
  "dep:leptos_axum",
  "dep:tokio",
]

[package.metadata.leptos]
bin-features = ["ssr"]
lib-features = ["hydrate"]
