name: Deploys demo site to GH pages

on:
  push:
    branches: ["master"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  call-nix-flake-check:
    uses: ./.github/workflows/nix-flake-check.yml

  build:
    runs-on: ubuntu-latest
    needs: call-nix-flake-check
    steps:
      - run: nix build .#demo --print-build-logs
      - name: Adjust permissions
        run: |
          chown -R $(id -u):$(id -g) ./result
          chmod -R a+rwx ./result
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./result

  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
