name: Run all checks and deploys demo site to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nixbuild/nix-quick-install-action@v25
      - run: nix flake check . --print-build-logs
      - run: nix build .#demo --print-build-logs
      - name: Adjust permissions
        run: |
          chown -R $(id -u):$(id -g) ./result
          chmod -R a+rwx ./result
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./result
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
